### ISSUE TITLE
npx node f

### ISSUE THREAD

**Issue by Tarang** [Reggionick/s3-deploy#24]
I keep getting this error

```
Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/node/12.20.0/x64/bin/npx'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/node/12.20.0/x64/bin/npx ENOENT
```

I'm a bit unsure what is causing it. I have copied and pasted the yaml on the README pretty much verbatim and used my credentials. I can see there is a related closed issue https://github.com/Reggionick/s3-deploy/issues/13 but it was not resolved.

**Comment by themakshter** [comment]
I am also facing this - any ideas why?

**Comment by themakshter** [comment]
I have fixed my issue.

@Tarang, perhaps the directory that you are trying to upload isn't present. Could you provide with details of your action?

**Comment by Tarang** [comment]
Pretty sure the directory is there, if i use s3 deploy directly it works fine

**Comment by Reggionick** [comment]
Hi @Tarang, do you still have this issue? Cloud you paste your action workflow?

**Comment by Tarang** [comment]
Pretty much the example and just changing the directory:

```
name: Example workflow for S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: dist
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.S3_BUCKET_REGION }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
```
