### ISSUE TITLE
Usage example update

### ISSUE THREAD

**Issue by coliff** [Reggionick/s3-deploy#45]
In the README Usage example:

```yml
uses: reggionick/s3-deploy@v3
with:
    folder: build
    bucket: ${{ secrets.S3_BUCKET }}
    dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
```

it is missing the required `region:` - do you think this should be added? The `dist-id` isn't required - maybe it could be removed?
