### ISSUE TITLE
Issue with folder option?

### ISSUE THREAD

**Issue by chaitanya-deep** [Reggionick/s3-deploy#63]

**Comment by Reggionick** [comment]
Which version are you using?

**Comment by chaitanya-deep** [comment]
Thank you for the quick response.

`reggionick/s3-deploy@v3`

**Comment by Reggionick** [comment]
We haven't made any change on the v3 of the action. Could you double check on your side?

**Comment by callum-hyland** [comment]
Same issue for me, no code changed in the action for months but randomly it's started pushing the root folder. Could be an internal Github change?
```
- name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: ./interface/build
```
![Screenshot 2022-04-08 at 09 50 34](https://user-images.githubusercontent.com/3671304/162400927-b999c313-87cb-4371-a052-af4db61cc1b9.png)

**Comment by ajainvivek** [comment]
Same issue for me. no code changes pushing the root folder.

**Comment by ajainvivek** [comment]
@Reggionick Any updates on this issue?

**Comment by Reggionick** [comment]
No, I can't work on this right now.. But any PR is welcome!

**Comment by palashkaria** [comment]
This caused our prod dashboard to go down, we have migrated away from using GH actions for this reason. Would recommend anyone else using this to pin the version that works.

**Comment by chaitanya-deep** [comment]
I'm not sure if this is the cause but in my case, the only change I notice is the Github job runner version change from 2.289.1 to 2.289.2. It's currently at version 2.290.1 but the issue seems to persist

<img width="1233" alt="Screenshot 2022-04-18 at 7 12 53 PM" src="https://user-images.githubusercontent.com/5744488/163816934-c0e3e58f-9a64-4685-9336-06e67d532ea7.png">

**Comment by tanmoyAtb** [comment]
Same issue here. We had to move to manual deploys for the time being.

**Comment by chaitanya-deep** [comment]
Hi,

For anyone else who came across this. I couldn't solve it with the action but found an alternate to fix it.
Edited my action yml file to replace this with aws cli.

```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy dashboard to bucket
        run: aws s3 sync ./packages/dashboard/build s3://<bucket-name>/<folder-path>/

      - name: Invalidate dashboard cloudfront
        run: aws cloudfront create-invalidation --distribution-id <dist-id> --paths "/<invalidation-path>/*"
```
